# Generated by Django 2.2.5 on 2019-12-04 21:56

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='data',
            new_name='date',
        ),
        migrations.AddField(
            model_name='blog',
            name='uid',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
