# Generated by Django 2.2.5 on 2019-12-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20191204_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='privacy',
            field=models.IntegerField(choices=[('Public', 1), ('Private', 0)], default=0),
        ),
    ]
