# Generated by Django 2.2.5 on 2019-12-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_blog_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='privacy',
            field=models.IntegerField(choices=[(1, 'Public'), (0, 'Private')], default=0),
        ),
    ]
